version: '3.8'
services:
  backend:
    build: ./backend
    container_name: api
    ports:
      - '4000:4000'

  frontend:
    build: ./front
    container_name: front
    ports:
        - '3000:3000'
    depends_on:
      - backend
